CREATE DATABASE CHAT_BOX;
USE CHAT_BOX;

CREATE TABLE[User](
    [ID]             [integer] IDENTITY(1,1) NOT NULL,
    [Codigo]         [uniqueidentifier]      NOT NULL,
    [Name]			 varchar(100)			 NOT NULL,
    [BirthDate]		 Date					 NOT NULL,
	[Email]			 varchar(150)			 NOT NULL,
    [Situation]		 [INT]					 NOT NULL

CONSTRAINT [PK_User] PRIMARY KEY NONCLUSTERED 
(
    [Codigo] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
        ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE UNIQUE CLUSTERED INDEX [CL_User] ON [User]
(
    [ID] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF,
        DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
